server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: product-app
            uri: http://localhost:8083
            predicates:
              - Path=/product/**
            filters:
              - name: CircuitBreaker
                args:
                  name: prodService
                  fallbackUri: forward:/prod-fallback

resilience4j:
  circuitbreaker:
    instances:
      prodService:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        minimum-number-of-calls: 10 # defines the minimum number of requests required before the Circuit Breaker starts calculating the failure rate.
        failure-rate-threshold: 50 #  The Circuit Breaker opens if 50% or more of the requests fail within the defined sliding window
        record-exceptions: # to identify which exceptions to record as failures.
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.lang.RuntimeException
        #        Play with ‘failureRateThreshold’, ‘recordExceptions’, ‘minimumNumberOfCalls’
        wait-duration-in-open-state: 10s
        register-health-indicator: true

  timelimiter:
    instances:
      prodService:
        timeout-duration: 3s
